config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :accounts

  resources :accounts do
    member do
      match 'add_nominee', via: %i[get post]
    end
    collection do
      get 'edit_nominee'
      delete 'remove_nominee'
      patch 'update_nominee'
    end
  end
  delete 'logout', to: 'sessions#destroy'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
  validates_uniqueness_of :email
  has_many :nominees, class_name: 'Nominee', dependent: :destroy, foreign_key: 'account_id'
  has_many :nominee_users, through: :nominees, source: :nominee
  has_many :nominators, class_name: 'Nominee', dependent: :destroy, foreign_key: 'nominee_id'
  has_many :nominated_by, through: :nominators, source: :account

  def self.find_or_create_default_account(email)
    Account.find_by_email(email) || Account.create(email: email, password: 'Test@123')
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nominee.rb
# frozen_string_literal: true

class Nominee < ApplicationRecord
  belongs_to :nominee, class_name: 'Account'
  belongs_to :account, class_name: 'Account'
  validates_uniqueness_of :nominee_id, scope: :account
  validate :nominee_id_cannot_be_account
  validate :valid_weightage_percentage?
  MAX_WEIGHTAGE = 100

  private

  # validation for nominee and account can't be same.
  def nominee_id_cannot_be_account
    errors.add(:nominee_id, "can't add yourself as nominee") if nominee_id == account_id
  end

  # check valid weightage percentage
  def valid_weightage_percentage?
    total_weight = (account.nominees.sum(&:weightage).to_f + weightage.to_f) if account&.nominees.present?
    return unless total_weight.present? && (total_weight > MAX_WEIGHTAGE)

    errors.add(:weightage, "Summation of weightage of all nominees shouldn't be > 100")
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

# Account class
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]
  before_action :set_nominee, only: %i[edit_nominee update_nominee remove_nominee]

  def add_nominee
    return unless params[:nominee].present?
    nominee_account = Account.find_or_create_default_account(params[:nominee][:email])
    nominee = current_account.nominees.find_by(nominee_id: nominee_account.id)
    nominee = if nominee.present?
                nominee.update(nominee_params)
              else
                current_account.nominees.create(nominee_id: nominee_account.id, weightage: params[:nominee][:weightage])
              end
    return unless nominee.errors.present?
    redirect_to add_nominee_account_path(current_account.id), notice: nominee.errors.full_messages.join.to_s
  end

  def edit_nominee; end

  def update_nominee
    if @nominee.update(nominee_params)
      redirect_to add_nominee_account_path(current_account.id)
    else
      render 'edit_nominee', notice: @nominee.errors.full_messages.join.to_s
    end
  end

  def remove_nominee
    @nominee.destroy
    redirect_to add_nominee_account_path(current_account.id), notice: 'Nominee deleted successfully'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find_by(id: params[:id])
  end

  def set_nominee
    @nominee = Nominee.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:username, :first_name, :last_name, :email)
  end

  def nominee_params
    params.require(:nominee).permit(:email, :weightage)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    if current_account.present?
      @nominees = current_account.nominee_users
      @nominated_by = current_account.nominated_by
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/accounts/add_nominee.html.erb
<div class="container">
	<% if current_account.nominees.any? %>
		<% @balance_weightage = 100 - (current_account.nominees.pluck(:weightage).sum) %>
		<h3> Hey <%=current_account.first_name %> your weightage balance is (<%= @balance_weightage.to_i %> %)</h3>
		<br>
		<h2>Nominees Details</h2>
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Email</th>
					<th>Firstname</th>
					<th>Lastname</th>
					<th>Weightage(%)</th>
					<th>Added on</th>
					<th> Actions </th>
				</tr>
			</thead>
			<tbody>
				<% current_account.nominees.each do |user| %>
					<tr>
						<td><%=h user.nominee.email %></td>
						<td><%=h user.nominee.first_name %></td>
						<td><%=h user.nominee.last_name %></td>
						<td><%=h user.weightage %></td>
						<td><%=h user.created_at %></td>
						<td><%= link_to 'Edit', edit_nominee_accounts_path(id: user.id), :class=>"btn btn-primary" %> <%= link_to 'Remove', remove_nominee_accounts_path(id: user.id), :confirm => 'Are you sure?', :method => :delete, :class=>"btn btn-danger" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>	
</div>	
<div class="container">
	<div class="row">
			<div class="col-8">
				<h2>Add Nominee Details</h2>
				<%= form_for :nominee,  url: add_nominee_account_path(current_account.id), method: "post", :class=>"form-horizontal" do |f| %>
					<div class="form-group">
						<label class="control-label col-sm-2" for="email">Email:</label>
						<div class="col-sm-10">
							<%= f.email_field :email, autofocus: true, autocomplete: "email" , :class=>"form-control", :required=>:true%>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-2" for="weightage">Weightage:</label>
						<div class="col-sm-10">
							<%= f.number_field :weightage, :class=>"form-control", :required=>:true%>
						</div>
					</div>
					<br>
					<div class="form-group">        
						<div class="col-sm-offset-2 col-sm-10">
							<%= f.submit "Add Nominee" , :class=>"btn btn-primary"%>
						</div>
					</div>	
				<% end %>
			</div>
			<div class="col-4">
				<div class="card">
					<div class="card-header">
						Featured
					</div>
					<div class="card-body">
						<h5 class="card-title"> File Nomination</h5>
						<p class="card-text">You can add details of more than one family member if you want to make more than one nomiee by clicking on 'Add Nominee' option.</p>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/accounts/edit_nominee.html.erb
<div class="container">
	<div class="row">
			<div class="col-8">
				<h2>Edit Nominee Details</h2>
				<%= form_for @nominee,  url: update_nominee_accounts_path(id: @nominee.id), method: "patch", :class=>"form-horizontal" do |f| %>
					
					<div class="form-group">
						<label class="control-label col-sm-2" for="weightage">Weightage:</label>
						<div class="col-sm-10">
							<%= f.number_field :weightage, :class=>"form-control", :required=>:true%>
						</div>
					</div>
					<br>
					<div class="form-group">        
						<div class="col-sm-offset-2 col-sm-10">
							<%= f.submit "Update Nominee" , :class=>"btn btn-primary"%>
						</div>
					</div>	
				<% end %>
			</div>
			<div class="col-4">
				<div class="card">
					<div class="card-header">
						Featured
					</div>
					<div class="card-body">
						<h5 class="card-title"> File Nomination</h5>
						<p class="card-text">You can add details of more than one family member if you want to make more than one nomiee by clicking on 'Add Nominee' option.</p>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/home/_users.html.erb
<table class="table table-hover table-light">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
  	<% users.each do |user| %>  
    	<tr>
	      <td><%= user.first_name %></td>
	      <td><%= user.last_name %></td>
	      <td><%= user.email %></td>
    	</tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<% if current_account.present? %>
	<div class="container">
		<section class="showcase">
			<div class="container-fluid p-0">
				<div class="row no-gutters">
					<div class="col-lg-12 ">
						<div> <h2>Welcome <%= current_account.first_name %></h2> </div>
						<p> Hey <%= current_account.first_name %> your account balance is <%= current_account.account_balance %></p>
						<div class="lead mb-0">
							You can do this by clicking here 	<%= link_to "Add nominee", add_nominee_account_path(current_account.id), method: :get %> . If you are adding multiple nominees, make sure to mention the % of holding that you want to allocate to each nominee so that the sum total is 100%.
						</div>
					</div>
				</div>				
				<br>
			</div>
		</section>
	</div>
	<br><br>
	<div class="container">
	  <div class="row">
			<div class="col-md-4 col-xl-3">
				<div class="card bg-primary text-white">
					<div class="card-block" style="padding:10px">
						<h6 class="text-center m-b-20">Nominators</h6>
						<h2 class="text-center"><i class="fa fa-cart-plus f-left"></i><span><%= @nominated_by.count %></span></h2>
						<br>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xl-3">
				<div class="card bg-dark text-white">
					<div class="card-block" style="padding:10px">
						<h6 class="text-center m-b-20">Nominees</h6>
						<h2 class="text-center"><i class="fa fa-rocket f-left"></i><span><%= @nominees.count %></span></h2>
						<br>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br><br>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<%if @nominated_by.present? %>
					<h4>Nominator Details</h4> 
					<%= render partial: "users", locals: {users: @nominated_by} %>
				<% else %>
					<div>No one added you as their nominee.</div>
				<% end %>
			</div>
			<div class="col-sm-6">
				<% if @nominees.present? %>
					<h4>Your Nominee Details</h4>
					<%= render partial: "users", locals: {users: @nominees} %>
				<% else%>
					<div>You haven't nominated anyone yet.</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Nomination Portal</a>
        <ul class="nav navbar-nav navbar-right">
          <% if current_account%>
           <!--  <li class="nav-item"><a href="#"><span class= "nav-link"></span><%#= current_account.email%></a></li> -->
            <li class="nav-item">
              <%= link_to current_account.email ,edit_account_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout",destroy_account_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>%>
            <li>
              <%= link_to "Sign Up",new_account_registration_path, class: "glyphicon glyphicon-user" %>
            </li>
            <li>
              <%= link_to "Login",new_account_session_path, class: "glyphicon glyphicon-log-in" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%#= link_to "Navbar",root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%#= link_to "Home",root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "About",root_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <!-- update user password-->
            <%= link_to current_user.email ,edit_account_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout",destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up",new_account_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login",new_account_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>